
algoritmo "Exemplo Procedimento"

var
n1, n2:real
nome:literal
inicio
procedimento mostra(a,b:real;c:literal)
inicio
escreval("O valor de n1 é: ", a)
escreval("O valor de n2 é: ", b)
escreval("O Nome é: ", c)
fimprocedimento

escreval("Informe o valor de n1: ")
leia(n1)
escreval("Informe o valor de n2: ")
leia(n2)
escreval("Informe o nome: ")
leia(nome)

mostra(n1,n2,nome)

fimalgoritmo
