//Faça um programa que fique mostrando a mensagem "Comando enquanto".
//A cada frase mostrada, dê a opção para que o usuário escolher se
//continua ou não S-Continuar N-Não continuar.

algoritmo "Continue ou Não-Enquanto"

var

cont: inteiro
S: caracter

inicio

enquanto S <> "n" faca
   escreval ("Comando enquanto")
   escreva ("S-Continuar ou N-Não continuar: ")
   leia(S)
fimenquanto

fimalgoritmo
