//Faça um algoritmo qye mostre até a tabuada do 5 resolvida.

//aula30/05/2022
algoritmo "Tabuáda de 1 a 5"

var
contador, conta:inteiro



inicio

para contador <- 1 ate 5 faca
   escreval("===============================================================================")
   para conta <- 0 ate 10 faca
      escreval(contador, " X ", conta, " = ", contador*conta)
   fimpara
fimpara

fimalgoritmo
